blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/<YOUR-ORG>/<YOUR-REPO>/discussions
    about: Use Discussions for Q&A and how-to questions
  - name: Read the docs
    url: https://<your-site-or-docs-url>
    about: Start here for guides and FAQs
